version: '3'

services:
    db:
        image: postgres

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
	depends_on:
      	    - db
    	command: >
      	    sh -c "python manage.py migrate && python manage.py shell < etymwn-dump.sql && python manage.py runserver 0.0.0.0:8000"