# Generated by Django 5.0.2 on 2024-03-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_follower',
            new_name='following',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
    ]
