# Generated by Django 5.0.2 on 2024-04-10 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=50)),
                ('meaning', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=50)),
                ('from_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_entries', to='entries.entry')),
                ('to_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_entries', to='entries.entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='related_entries',
            field=models.ManyToManyField(related_name='related_entries_reverse', through='entries.EntryRelations', to='entries.entry'),
        ),
    ]
