# Generated by Django 5.0.2 on 2024-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
