# Generated by Django 5.0.2 on 2024-04-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='featured',
        ),
        migrations.CreateModel(
            name='EntriesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=50)),
                ('from_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from_entry', to='entries.entry')),
                ('to_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to_entry', to='entries.entry')),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='related_entries',
            field=models.ManyToManyField(related_name='related_entries_reverse', through='entries.EntriesRelation', to='entries.entry'),
        ),
        migrations.CreateModel(
            name='WordFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordfamilies_familyword', to='entries.entry')),
                ('primeetymon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordfamilies_primeetymon', to='entries.entry')),
            ],
        ),
        migrations.DeleteModel(
            name='EntryRelations',
        ),
    ]
