# Generated by Django 5.0.2 on 2024-04-18 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_remove_entry_featured_entriesrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entriesrelation',
            name='from_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_fromentry', to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='entriesrelation',
            name='to_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_toentry', to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='wordfamily',
            name='familyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordfamilies_as_familyword', to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='wordfamily',
            name='primeetymon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordfamilies_as_primeetymon', to='entries.entry'),
        ),
    ]
