# Generated by Django 5.0.2 on 2024-04-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entriesrelation_from_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='latinized_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='specialized_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
