# Generated by Django 5.0.2 on 2024-04-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_latinized_name_entry_specialized_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='specialized_name',
            new_name='wiktionary_name',
        ),
    ]
