# Generated by Django 5.0.2 on 2024-04-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_entry_search_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='search_name',
            new_name='english_name',
        ),
    ]
