# Generated by Django 5.0.2 on 2024-04-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_rename_search_name_entry_english_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordFamily',
            new_name='FamilialRelation',
        ),
    ]
