# Generated by Django 5.0.2 on 2024-04-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_rename_wordfamily_familialrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='english_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
