# Generated by Django 5.0.2 on 2024-04-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_alter_entry_english_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='meaning',
        ),
    ]
